language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.1.2

env:
  - "CI_DB_ADAPTER=sqlite3"
before_script:
  - cd spec/dummy
  - bundle install --without debug
  - bundle update helpdesk --without debug
  - bundle exec rake helpdesk:prepare_ci_env
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../..
script:
  - bundle exec rspec
